version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_INTERNAL_ADVERTISED_HOSTNAME}:${KAFKA_INTERNAL_ADVERTISED_PORT},PLAINTEXT_HOST://${KAFKA_EXTERNAL_ADVERTISED_HOSTNAME}:${KAFKA_EXTERNAL_ADVERTISED_PORT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # KAFKA_CREATE_TOPICS: "flightdata:1:1"

  flight-producer:
    build: .
    container_name: flight-producer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER_URL: ${KAFKA_BROKER_URL}
      FLASK_DEBUG: ${FLASK_DEBUG}
    command: >
      sh -c "
        echo 'Waiting for Kafka to be ready...' &&
        sleep 15 &&
        python flight.py
      "

  flight-app:
    build: .
    container_name: flight-app
    depends_on:
      - kafka
    ports:
      - "5001:5001"
    environment:
      KAFKA_BROKER_URL: ${KAFKA_BROKER_URL}
      FLASK_DEBUG: ${FLASK_DEBUG}
    command: >
      sh -c "
        echo 'Waiting for Kafka to be ready...' &&
        sleep 15 &&
        python app.py
      "

networks:
  default:
    name: kafka-network 